package oxygen.util

object PackageManager {
  const val PERMISSION_GRANTED = 0
  const val PERMISSION_DENIED = -1

  const val GET_PERMISSIONS = 0x0000_0080
  const val GET_ACTIVITIES = 0x0000_0001
  const val GET_RECEIVERS = 0x0000_0002
  const val GET_SERVICES = 0x0000_0004
  const val GET_PROVIDERS = 0x0000_0008
  const val GET_INTENT_FILTERS = 0x0000_0020
  const val GET_META_DATA = 0x0000_0080

  const val COMPONENT_ENABLED_STATE_DEFAULT = 0
  const val COMPONENT_ENABLED_STATE_ENABLED = 1
  const val COMPONENT_ENABLED_STATE_DISABLED = 2

  const val INSTALL_LOCATION_AUTO = 0
  const val INSTALL_LOCATION_INTERNAL_ONLY = 1
  const val INSTALL_LOCATION_PREFER_EXTERNAL = 2

  const val SIGNATURE_MATCH = 0
  const val SIGNATURE_NEITHER_SIGNED = 1
  const val SIGNATURE_FIRST_NOT_SIGNED = -1
  const val SIGNATURE_SECOND_NOT_SIGNED = -2
  const val SIGNATURE_NO_MATCH = -3
  const val SIGNATURE_UNKNOWN_PACKAGE = -4

  const val VERSION_CODE_HIGHEST = -1

  const val GET_ACTIVITY_INFO = 0x0000_0001
  const val GET_CONFIGURATIONS = 0x0000_4000
}
